# Lecture 1: Data Processing with NumPy

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.  

The key features of numpy are:

- ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient.  There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
- Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
- Vectorization: enables numeric operations on ndarrays.
- Input/Output: simplifies reading and writing of data from/to file.

<b>Additional Recommended Resources:</b><br>
[Numpy Documentation](https://numpy.org/doc/stable/reference/)

[Python for Data Analysis](https://wesmckinney.com/book/) by Wes McKinney

[Python Data science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/) by Jake VanderPlas



## Getting started with ndarray

**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy.  Let's get started by creating ndarrays using the numpy package.

**How to create Rank 1 numpy arrays:**

In [ ]:
import numpy as np

an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(type(an_array))              # The type of an ndarray is: "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [ ]:
# test the shape of the array we just created, it should have just one dimension (Rank 1)
an_array.shape

(3,)

In [ ]:
# because this is a 1-rank array, we need only one index to accesss each element
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [ ]:
# ndarrays are mutable, here we change an element of the array
an_array = np.array([3, 33, 333])  # Create a rank 1 array

print("original array",an_array)
an_array[1] = 69

print("mutable array",an_array)

original array [  3  33 333]
mutable array [  3  69 333]


**How to create a Rank 2 numpy array:**

A rank 2 **ndarray** is one with two dimensions.  Notice the format below of [ [row] , [row] ].  2 dimensional arrays are great for representing matrices which are often useful in data science.

In [ ]:
another = np.array([[11,12,13],[21,22,23]])   # Create a rank 2 array

print(another)  # print the array

print("The shape is 2 rows, 3 columns: ", another.shape)  # rows x columns

print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 ,  12 ,  21


**There are many way to create numpy arrays:**

Here we create a number of different size arrays with different shapes and different pre-filled values.  numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.

In [ ]:
import numpy as np

# create a 2x2 array of zeros
ex1=np.zeros((2,2)) #สร้าง 2 มิติทีมีเลข 0
print(ex1)

[[0. 0.]
 [0. 0.]]


In [ ]:
# create a 2x2 array filled with 9.0 #เติมค่านึงไปใน array
ex2 = np.full((2,2), 9.0) #บอกมิติเป็น 2x2 เติมค่า 9.0
ex2

array([[9., 9.],
       [9., 9.]])

In [ ]:
# create a 2x2 matrix with the diagonal 1s and the others 0 (identity matrix)
ex3 = np.eye(2,2) #เมทริกซ์เอกลักษณ์ มี 0 ไปหมดแต่ตรงที่เป็นมุมทแยงเป็นเลข 1
ex3

array([[1., 0.],
       [0., 1.]])

In [ ]:
# create an array of ones
ex4 = np.ones((1,2)) #1 dimention 1 row 2 column
ex4

array([[1., 1.]])

In [ ]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x1 array
print(ex4.shape)

# which means we need to use two indexes to access an element
ex4[0,1] #แม้ว่าจะมี row เดียวแต่ต้อง access 2 ค่า เพราะเป็น 2 bits

(1, 2)


1.0

In [ ]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
ex5

array([[0.86792717, 0.78688557],
       [0.07389271, 0.43929835]])

## Array Indexing

**Slice indexing:**

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays.

In [ ]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
an_array

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.

In [ ]:
a_slice = an_array[0:2,1:3] #row 0,1 ไม่เอา 2 column 1,2 ไม่เอา 3
a_slice

array([[12, 13],
       [22, 23]])

When you modify a slice, you actually modify the underlying array.

In [ ]:
print("Before:", an_array[0, 1])   #inspect the element at 0, 1
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1] ตำแหน่ง [0,0] ใน a_slice เหมือน ตำแหน่ง [0,1] ใน an_array เปลี่ยนจาก 12 เป็น 1000
print("After:", an_array[0, 1])

Before: 12
After: 1000


**Use both integer indexing & slice indexing**

We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [ ]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
an_array

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [ ]:
# Using both integer indexing & slicing generates an array of lower rank // slice ให้เหลือ 1D
    # Rank 1 view
row_rank1 = an_array[1,:]    # Rank 1 view // เอา row 1 และเอาทุก column // ถ้าใส่ [1:2,:] จะนับว่าเป็น 2D อยู่ output = [[]] 2 bracket shape ออกมา 2 ค่า
print(row_rank1, row_rank1.shape)  # notice only a single [] // จะเหลือค่าเดียว

[21 22 23 24] (4,)


In [ ]:
# Slicing alone: generates an array of the same rank as the an_array
 # Rank 2 view
row_rank2 = an_array[:2, 1:3]
print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

[[12 13]
 [22 23]] (2, 2)


In [ ]:
#We can do the same thing for columns of an array:

col_rank1 = an_array[:, 1] #1D
col_rank2 = an_array[:, 1:2] #2D

print(col_rank1, col_rank1.shape)  # Rank 1 1 ค่า
print()
print(col_rank2, col_rank2.shape)  # Rank 2 2 ค่า

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


**Array Indexing for changing elements**

Sometimes it's useful to use an array of indexes to access or change elements.

In [ ]:
# Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [ ]:
# Create an array of indices
col_indices = np.array([0, 1, 2, 0]) #เข้าถึง column 0 1 2 0 = 11 22 33 41
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4) # เข้าถึง row ที่ 0,1,2,3 arange เป็น method เข้าถึง row
print('\nRows indices picked : ', row_indices)
#output คือ index ที่เราต้องการเลือกออกมา


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [ ]:
# Examine the pairings of row_indices and col_indices.  These are the elements we'll change next.
for row,col in zip(row_indices,col_indices): # ใช้คำสั่ง zip คือการรวม row and col ให้ output ออกมาเป็นคู่ๆ
    print(row, ", ",col) #this is not numpy

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [ ]:
# Select one element from each row // ไม่ต้องมา loop เหมือนข้างบน np สามารถบอก row col ที่ต้องการได้เลย
print('Values in the array at those indices: ',an_array[row_indices, col_indices])

Values in the array at those indices:  [11 22 33 41]


In [ ]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 1000 #บวกค่าไป 1000 ตาม row col ที่เราเลือกไว้
print('\nChanged Array:')
print(an_array)


Changed Array:
[[1011   12   13]
 [  21 1022   23]
 [  31   32 1033]
 [1041   42   43]]


## Boolean Indexing

**Array Indexing for changing elements:**

In [ ]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
an_array

array([[11, 12],
       [21, 22],
       [31, 32]])

In [ ]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (an_array > 15) #เอาตัวใน array ว่า > 15 ไหม้ ถ้ามากกว่า = T น้อยกว่า = F
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is a same size ndarray as an_array which is filled with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15.

In [ ]:
# we can now select just those elements which meet that criteria
an_array[filter] #ทำ 2 step รวมกับก่อนหน้า
# Since a boolean mask can have different number of True in each row or column, the indexing can't preserve shape - it has to return a 1d result.

array([21, 22, 31, 32])

In [ ]:
# For short, we could have just used the approach below without the need for the separate filter array.
an_array[an_array > 15] # ทำทีเดียว

array([21, 22, 31, 32])

What is particularly useful is that we can actually change elements in the array applying a similar logical filter.  Let's add 100 to all the even values.

In [ ]:
an_array[an_array % 2 == 0] #เลือกเฉพาะเลขคู่ เป็น 1D เพราะเป็น view ของมันไม่ใช่ตัวเดิม

array([12, 22, 32])

In [ ]:
an_array[an_array % 2 == 0] +=100
an_array # เป็น 2D เพราะเป็นการแก้ array ตัวเดิมที่เป็น 2D

array([[ 11, 112],
       [ 21, 122],
       [ 31, 132]])

## Datatypes and Array Operations

**Datatypes:**

In [ ]:
ex1 = np.array([11, 12]) # Python assigns the data type
ex1.dtype

dtype('int64')

In [ ]:
ex2 = np.array([11.0, 12.0]) # Python assigns the data type
ex2.dtype

dtype('float64')

In [ ]:
ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the data type
ex3.dtype #บังคับให้เป็น int

dtype('int64')

In [ ]:
# you can use this to force floats into integers (using floor function)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print() #ไม่สามารถบังคับ floats to int ได้มันจะตัดทศนิยมออก
ex4

int64



array([11, 12])

In [ ]:
# you can use this to force integers into floats if you anticipate
# the values may change to floats later
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
ex5

float64



array([11., 21.])

**Arithmetic Array Operations:**

In [ ]:
x = np.array([[111,112],[121,122]], dtype=np.int64)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [ ]:
# add
print(x + y)         # The plus sign works
print() # บวกตรงๆได้
print(np.add(x, y))  # so does the numpy function "add"

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [ ]:
# subtract
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [ ]:
# multiply
print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [ ]:
# divide
print(x / y)
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [ ]:
# square root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [ ]:
# exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


## Statistical Methods, Sorting, and Set Operations

**Basic Statistical Operations:**

In [ ]:
# setup a random 2 x 5 matrix
arr = 10 * np.random.randn(2,5) #randn = randnormal 2 rows 5 col
arr

array([[ -1.86109474,   2.73635014,   7.31612031, -16.33075584,
         -5.17921322],
       [  3.10857825,  -1.66686617,  -6.55336486,  -0.59138482,
         -6.8585168 ]])

In [ ]:
# compute the mean for all elements
arr.mean()

-2.5880147734122305

In [ ]:
# compute the means by row
arr.mean(axis = 1) # หมายถึงทุก column ใน row เอามาคิด จะได้ row ใหม่

array([-2.66371867, -2.51231088])

In [ ]:
# compute the means by column
arr.mean(axis = 0)

array([ 0.62374176,  0.53474198,  0.38137773, -8.46107033, -6.01886501])

In [ ]:
# sum all the elements
arr.sum()

-40.18577362031842

In [ ]:
# compute the medians by rows
np.median(arr,axis = 1 ) #ต้องบอกว่าหา array ตัวไหน และ axis อะไร

array([-9.66457745, -0.26387344])

**Sorting:**

In [ ]:
# create a 10 element array of randoms
np.random.seed(10)
unsorted = np.random.randn(10)

unsorted

array([ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597,
       -0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021])

In [ ]:
# create copy and sort
sorted = np.array(unsorted)
# inplace sorting
sorted.sort()

print(sorted)
print()
print(unsorted)

[-1.54540029 -0.72008556 -0.17460021 -0.00838385  0.00429143  0.10854853
  0.26551159  0.62133597  0.71527897  1.3315865 ]

[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597 -0.72008556
  0.26551159  0.10854853  0.00429143 -0.17460021]


**Finding Unique elements:**

In [ ]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array)) #ตัวที่ซ้ำ

[1 2 4]


**Set Operations with np.array data type:**

In [ ]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [ ]:
print( np.intersect1d(s1, s2) )

['bulb' 'chair']


In [ ]:
print( np.union1d(s1, s2) )

['bulb' 'chair' 'desk' 'lamp']


In [ ]:
print( np.setdiff1d(s1, s2) ) # elements in s1 that are not in s2

['desk']


In [ ]:
print( np.in1d(s1, s2) ) #which element of s1 is also in s2

[False  True  True]


## Broadcasting

Introduction to broadcasting

For more details, please see:

https://numpy.org/devdocs/user/basics.broadcasting.html

In [ ]:
import numpy as np

start = np.zeros((4,3))
start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2]) #1D มี 3 ค่า
print(add_rows.shape)
add_rows

(3,)


array([1, 0, 2])

In [ ]:
 # add to each row of 'start' using broadcasting
y = start + add_rows
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [ ]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]]) #2D
add_cols = add_cols.T #T = Transpose swip row and col

add_cols

array([[0],
       [1],
       [2],
       [3]])

In [ ]:
# add to each column of 'start' using broadcasting
y = start + add_cols #เอาจาก start(4x3) มา compat กับ add_col(4x1)
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [ ]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])
start + add_scalar

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Example from the slides:

In [ ]:
# create our 3x4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arrA

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# create our 1x4 array
arrB = np.array([0,1,0,2])
arrB

array([0, 1, 0, 2])

In [ ]:
# add the two together using broadcasting
arrA + arrB

array([[ 1,  3,  3,  6],
       [ 5,  7,  7, 10],
       [ 9, 11, 11, 14]])

## Speedtest: ndarrays vs lists

First setup paramaters for the speed test. We'll be testing time to sum elements in an ndarray versus a list.

In [ ]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

In [ ]:
# create the ndarray with values 0,1,2...,size-1
nd_array = arange(size)
type(nd_array)

numpy.ndarray

In [ ]:
# timer expects the operation as a parameter,
# here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" %
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000170 seconds


In [ ]:
# create the list with values 0,1,2...,size-1
a_list = list(range(size))
type(a_list)

list

In [ ]:
# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" %
 (timer_list.timeit(timeits)/timeits))
#ต่างกัน 10 เท่า

Time taken by list:  0.006217 seconds


## Read or Write to Disk

Binary Format:

In [ ]:
x = np.array([ 23.23, 24.24] )

In [ ]:
np.save('an_array', x)

In [ ]:
np.load('an_array.npy')

array([23.23, 24.24])

Text Format:

In [ ]:
np.savetxt('array.txt', X=x, delimiter=',')

In [ ]:
#!type in Windows, !cat in Unix machine such as in Colab
!cat array.txt

2.323000000000000043e+01
2.423999999999999844e+01


In [ ]:
np.loadtxt('array.txt', delimiter=',')

array([23.23, 24.24])

## Additional Common ndarray Operations

**Dot Product on Matrices and Inner Product on Vectors:**

In [ ]:
# determine the dot product of two matrices
# for 2d array, it is a multiplication
x2d = np.array([[1,2],[3,4]])
y2d = np.array([[5,6],[7,8]])

print(x2d.dot(y2d)) #(1*5)+(2*7),(1*6)+(2*8),(3*5)+(4*7),(3*6)+(4*8) // มันคือการคูณเมทริกซ์
print()
print(np.dot(x2d, y2d))

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


In [ ]:
# determine the inner product of two vectors
# for 1darray it is the inner product
a1d = np.array([9 , 8 ])
b1d = np.array([10, 10])
# 9 * 10 + 8 * 10
print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

170

170


In [ ]:
# dot produce on an array and vector
print(x2d.dot(a1d)) #(1*9)+(2*8) = 25 , (3*9)+(4*8) = 59
print()
print(np.dot(x2d, a1d))

[25 59]

[25 59]


**Element-wise Functions:**

For example, let's compare two arrays values to get the maximum of each.

In [ ]:
# random array
x = np.random.randn(8)
x

array([ 0.43302619,  1.20303737, -0.96506567,  1.02827408,  0.22863013,
        0.44513761, -1.13660221,  0.13513688])

In [ ]:
# another random array
y = np.random.randn(8)
y

array([ 1.484537  , -1.07980489, -1.97772828, -1.7433723 ,  0.26607016,
        2.38496733,  1.12369125,  1.67262221])

In [ ]:
# returns element wise maximum between two arrays
# เทียบ 2 ตัวแล้ว ret ค่าที่ max สุดออกมา
np.maximum(x, y)

array([ 1.484537  ,  1.20303737, -0.96506567,  1.02827408,  0.26607016,
        2.38496733,  1.12369125,  1.67262221])

**Reshaping array:**

In [ ]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
arr #มี array 20 ค่า

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5) # สามารถ reshape ให้เป็น 4x5 ได้

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**Transpose:**

In [ ]:
# transpose // row to column and col to row
ex1 = np.array([[11,12],[21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

**Indexing using where():**

In [ ]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, True, True, False, True])

In [ ]:
# When True yields x, otherwise yields y
out = np.where(filter, x_1, y_1) #ค่าไหนมาจาก x เป็น True จาก y เป็น False ที่เราได้ filter บอกไว้แล้ว
print(out)

[ 1  2  3 44  5]


In [ ]:
mat = np.random.rand(5,5)
mat

array([[0.8052232 , 0.52164715, 0.90864888, 0.31923609, 0.09045935],
       [0.30070006, 0.11398436, 0.82868133, 0.04689632, 0.62628715],
       [0.54758616, 0.819287  , 0.19894754, 0.8568503 , 0.35165264],
       [0.75464769, 0.29596171, 0.88393648, 0.32551164, 0.1650159 ],
       [0.39252924, 0.09346037, 0.82110566, 0.15115202, 0.38411445]])

In [ ]:
np.where( mat > 0.5, 1000, -1) #ใส่เงื่อนไข ถ้าค่าไหน > 0.5 is 1000 if < 0.5 is -1

array([[1000, 1000, 1000,   -1,   -1],
       [  -1,   -1, 1000,   -1, 1000],
       [1000, 1000,   -1, 1000,   -1],
       [1000,   -1, 1000,   -1,   -1],
       [  -1,   -1, 1000,   -1,   -1]])

**"any" or "all" conditionals:**

In [ ]:
arr_bools = np.array([ True, False, True, True, False ])

In [ ]:
arr_bools.any() #อย่างน้อยตัวนึงมี True output ret True

True

In [ ]:
arr_bools.all() #ทุกอันต้องเป็น True

False

**Random Number Generation:**

In [ ]:
Y = np.random.normal(size = (1,5))[0] #select row 0
print(Y)

[ 1.28227668 -0.17180538  0.57765806 -1.47497488  0.07878845]


In [ ]:
Z = np.random.randint(low=2,high=50,size=4) #rand int 2 - 50  4 ตัว
print(Z)

[27 11 39  2]


In [ ]:
np.random.permutation(Z) #return a new ordering of elements in Z

array([ 2, 27, 11, 39])

In [ ]:
np.random.uniform(size=4) #uniform distribution

array([0.2350386 , 0.65996495, 0.21495319, 0.20304662])

In [ ]:
np.random.normal(size=4) #normal distribution

array([ 0.91841365, -1.3193914 , -0.56172842,  0.20538457])

**Merging data sets:**

In [ ]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[19 43]
 [18 43]]

[[28 14]
 [32 19]]


In [ ]:
#vertical stack
np.vstack((K,M)) #เอามาต่อกันให้มี row มากขึ้น

array([[19, 43],
       [18, 43],
       [28, 14],
       [32, 19]])

In [ ]:
np.hstack((K,M)) #เอามาต่อกันให้มี col มากขึ้น

array([[19, 43, 28, 14],
       [18, 43, 32, 19]])

In [ ]:
np.concatenate([K, M], axis = 0) #สามารถใช้ concatenate แทน v.stack ได้  axis 0 คือให้มี row เยอะขึ้น

array([[19, 43],
       [18, 43],
       [28, 14],
       [32, 19]])

In [ ]:
np.concatenate([K, M.T], axis = 1) #สามารถใช้ concatenate แทน h.stack ได้  axis 1 คือให้มี col เยอะขึ้น

array([[19, 43, 28, 32],
       [18, 43, 14, 19]])